### ISSUE TITLE
Mesh's name

### ISSUE THREAD

**Issue by kororro** [vpenades/MonoScene#10]
Can I get names of meshes somewhere? (important when picking)

Added this to ModelInstance.cs  DrawOpaqueParts():
Console.WriteLine("DrawOpaqueParts()   meshname: " + mesh.Name);

but that mesh.Name is always null.

**Comment by vpenades** [comment]
there's still a lot of stuff to be filled, not only names, but also extra tags, etc.

Right now the project is on hold, because I hit a critical bug in monogame that's pending to be fixed. Pull request is ready for review, but seems everybody's busy, so don't expect much development for the rest of the year
