### ISSUE TITLE
Model rendering has colour artifacts

### ISSUE THREAD

**Issue by absoluteAquarian** [vpenades/MonoScene#12]
When rendering models via `ModelDrawingContext.DrawModelInstance()` and `ModelDrawingContext.DrawSceneInstances()`, brown and green colour artifacts appear on the rendered models.

The artifacts do not appear when rendering the model in something like 3D Viewer.

The model ingame:
![image](https://user-images.githubusercontent.com/30454621/206268356-7be6e185-f9fa-4e78-99a9-edb91a1b3b69.png)

The model in 3D Viewer:
![image](https://user-images.githubusercontent.com/30454621/206268470-670294be-c08b-42b3-bc96-f79e2a654b3b.png)

This happens with all `.glb` models exported from Blender, not just this one.

**Comment by absoluteAquarian** [comment]
Never mind, the weird colors were due to the lights in the `PBREnvironment` variable that I was using.

**Comment by vpenades** [comment]
This is also due to double sided surfaces.

glTF specification states that a model with double sided surfaces should be rendered correctly, regardless of which side is visible; consider a thin sheet of paper that can be seen from both sides.

But in that case, model wise, the normals are set for one of the sides, and for the other side, the normals needs to be reversed. What happens is that the normal and visibility is evaluated per pixel, and at the outline of the model, the normal is incorrectly reversed, _per pixel_

I lifted huge chunks of code from the official glTF shader code, and tried to adapt it to monogame shader antics, so it's at the very limit, so I'm not going to fix any of this.

Best thing is to avoid double sided surfaces except for obvious use cases like leafs and actual thin surfaces.

**Comment by absoluteAquarian** [comment]
Noted.  I'll mention this to the other devs
